ALTER TABLE `user`
    MODIFY COLUMN `first_name` VARCHAR(50) NOT NULL,
    MODIFY COLUMN `last_name` VARCHAR(50) NOT NULL,
    MODIFY COLUMN `bonus` INTEGER DEFAULT 0,
    MODIFY COLUMN `phone` VARCHAR(20);
